# name: Auto Merge Upstream ver/1.20.4

# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:

# jobs:
#   auto-merge:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.RELEASE_KEY }}

#       - name: Set up Git
#         run: |
#           git config user.name "${{ secrets.NAME }}"
#           git config user.email "${{ secrets.EMAIL }}"
#           git remote add upstream https://github.com/PaperMC/Folia

#       - name: Fetch upstream changes
#         run: git fetch upstream

#       - name: Switch to branch
#         run: git checkout -b ver/1.20.4

#       - name: Merge upstream changes
#         run: |
#           git merge upstream/master --allow-unrelated-histories -Xtheirs

#       - name: Configure Git with Secret
#         run: |
#           git config --global user.signingkey ${{ secrets.RELEASE_KEY }}

#       - name: Push changes
#         run: git push -f origin ver/1.20.4

#       - name: Cleanup
#         run: |
#           git remote remove upstream

name: '[V2]Auto Merge Upstream ver/1.20.4'

on:
  schedule:
    - cron: "0 * * * *" # 每小时执行一次 检查上游是否有更新
  workflow_dispatch:

jobs:
  auto-merge-and-check-updates:
    runs-on: ubuntu-latest
    env:
      UPSTREAM: 'https://github.com/PaperMC/Folia' # 上游仓库地址
      UPSTREAM_BRANCH: 'master' # 上游分支变量
      LOCAL_BRANCH: 'ver/1.20.4' # 本地分支变量

    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_KEY }}

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.NAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git remote add upstream ${{ env.UPSTREAM }}

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Check for updates
        run: |
         UPSTREAM_HASH=$(git rev-parse upstream/${{ env.UPSTREAM_BRANCH }})
         echo "UPSTREAM_HASH=$UPSTREAM_HASH"
         echo "UPSTREAM_HASH=$UPSTREAM_HASH" >> $GITHUB_ENV
        
         CURRENT_HASH=$(git rev-parse ${{ env.LOCAL_BRANCH }})
         echo "CURRENT_HASH=$CURRENT_HASH"
         echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV
        
         if [ "$UPSTREAM_HASH" != "$CURRENT_HASH" ]; then
          echo "updated=true" >> $GITHUB_ENV
          echo "Upstream repository has been updated."
         else
          echo "No updates found in the upstream repository."
         fi

      # 如果上游有更新，则合并这些更新
      - name: Merge and push if updated
        if: env.updated == 'true'
        run: |
          git checkout -b ${{ env.LOCAL_BRANCH }}
          git merge upstream/${{ env.UPSTREAM_BRANCH }} --allow-unrelated-histories -Xtheirs
          git config --global user.signingkey ${{ secrets.RELEASE_KEY }}
          git push -f origin ${{ env.LOCAL_BRANCH }}

      # 清理操作，删除添加的远程仓库
      - name: Cleanup
        run: |
          git remote remove upstream
